name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android Build Tools
      run: sdkmanager "build-tools;33.0.2"
    
    - name: Install required plugins
      run: |
        cordova plugin add cordova-plugin-speech-recognition
        cordova plugin add cordova-plugin-android-permissions
        cordova plugin add cordova-plugin-androidx
        cordova plugin add cordova-plugin-androidx-adapter


    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    
    - name: Install Cordova
      run: npm install -g cordova
    
    - name: Install dependencies
      run: npm install
    
    - name: Add Android platform
      run: cordova platform add android
    
    - name: Install required plugins
      run: |
        cordova plugin add cordova-plugin-speech-recognition
        cordova plugin add cordova-plugin-android-permissions
    
    - name: Build Debug APK
      run: cordova build android --debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
